spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: non
      
  jackson:
    parser:
      allow-unquoted-field-names: true

server:
    port: 8080
    
  
